Document: opencart
Title: Debian opencart Manual
Author: <insert document author here>
Abstract: This manual describes what opencart is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/opencart/opencart.sgml.gz

Format: postscript
Files: /usr/share/doc/opencart/opencart.ps.gz

Format: text
Files: /usr/share/doc/opencart/opencart.text.gz

Format: HTML
Index: /usr/share/doc/opencart/html/index.html
Files: /usr/share/doc/opencart/html/*.html
